[build]
builder = "python"
version = "3.11.10"

[install]
commands = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"


[options]
cache = ["~/.cache/pip"]
